spring.application.name=currency-conversion
server.port=8100

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*

eureka.client.serviceUrl.defaultZone=https://stunning-carnival-qp76g4q57p42x9j9-8761.app.github.dev/eureka
